# استفاده از آخرین نسخه از پایتون به عنوان تصویر پایه
FROM python:latest

# تعریف پوشه کاری در داخل کانتینر
WORKDIR /app

# کپی کردن فایل‌های مورد نیاز برای اجرای ربات به پوشه کاری
COPY requirements.txt .
COPY bot.py .

# نصب وابستگی‌های پروژه
RUN pip install --no-cache-dir -r requirements.txt

# تعریف متغیر محیطی TOKEN برای توکن ربات
ENV TOKEN "6152013499:AAFfPeG1JXv6uIZizBwFqV6OSW42yR9EpLk"

# تنظیم دستور اجرای ربات
CMD ["python", "bot.py"]
