View application logs as generated by the application running on
the Fly platform.

Logs can be filtered to a specific instance using the --instance/-i flag or
to all instances running in a specific region using the --region/-r flag.

By default logs are continually streamed until the command is aborted.
Use --no-tail to only fetch the logs in the buffer.


## Usage
~~~
fly logs [flags]
~~~

## Options

~~~
  -a, --app string       Application name
  -c, --config string    Path to application configuration file
  -h, --help             help for logs
  -j, --json             JSON output
      --machine string   Filter by machine ID
  -n, --no-tail          Do not continually stream logs
  -r, --region string    The target region (see 'flyctl platform regions')
~~~

## Global Options

~~~
  -t, --access-token string   Fly API Access Token
      --debug                 Print additional logs and traces
      --verbose               Verbose output
~~~

## See Also

* [fly](/docs/flyctl/help/)	 - The Fly.io command line interface

